package server

import (
	_ "github.com/apidet/go-api-service/docs" // generated by `swag init`
	"github.com/apidet/go-api-service/internal/middleware"
	"github.com/apidet/go-api-service/pkg/token"
	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

// registerRoutes ผูก route ทั้งหมด — แยก operational (root) ออกจาก API (versioned)
func registerRoutes(r *gin.Engine, h Handlers, tm *token.Manager) {
	// operational endpoints (ไม่ versioned — ใช้กับ k8s probe / LB)
	r.GET("/healthz", h.Health.Liveness)
	r.GET("/readyz", h.Health.Readiness)

	// Swagger UI: http://localhost:8080/swagger/index.html
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	// API v1
	v1 := r.Group("/api/v1")
	{
		// public — auth
		auth := v1.Group("/auth")
		{
			auth.POST("/login", middleware.RateLimit(5, 5), h.Auth.Login) // 5/นาที/IP
			auth.POST("/refresh", h.Auth.Refresh)
			auth.POST("/logout", middleware.Auth(tm), h.Auth.Logout)
		}
		// protected — customers (ต้องมี access token)
		customers := v1.Group("/customers")
		customers.Use(middleware.Auth(tm))
		{
			customers.GET("", h.Customer.List)
			customers.GET("/profile", h.Customer.GetProfile)
			customers.PATCH("/profile", h.Customer.UpdateProfile) // แก้โปรไฟล์ตัวเอง (id จาก token)
		}
		// protected — ticket (ต้องมี access token)
		tickets := v1.Group("/tickets")
		tickets.Use(middleware.Auth(tm))
		{
			tickets.GET("/active", h.Ticket.GetActiveTicket) // ticket active ของตัวเอง (id จาก token)
		}
	}
}
