package server

import (
	_ "github.com/apidet/go-api-service/docs" // generated by `swag init`
	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

// registerRoutes ผูก route ทั้งหมด — แยก operational (root) ออกจาก API (versioned)
func registerRoutes(r *gin.Engine, h Handlers) {
	// operational endpoints (ไม่ versioned — ใช้กับ k8s probe / LB)
	r.GET("/healthz", h.Health.Liveness)
	r.GET("/readyz", h.Health.Readiness)

	// Swagger UI: http://localhost:8080/swagger/index.html
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	// API v1
	v1 := r.Group("/api/v1")
	{
		customers := v1.Group("/customers")
		{
			customers.GET("", h.Customer.List)
			customers.GET("/:id", h.Customer.GetByID)
		}
	}
}
